<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
	<NoWarn>$(NoWarn);1591</NoWarn>
	<UserSecretsId>dbd57607-d4ce-4045-8ecd-9565ae644590</UserSecretsId>
   </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.27" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InventarioApi.Application\InventarioApi.Application.csproj" />
    <ProjectReference Include="..\InventarioApi.Infrastructure\InventarioApi.Infrastructure.csproj" />
  </ItemGroup>

</Project>
